name: "Checks (alpine, many platforms)"

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  linux-alpine:
    runs-on: ubuntu-latest
    name: linux-alpine-${{ matrix.platform }}
    # abort if x86_64 fails
    continue-on-error: ${{ matrix.platform != 'x86_64' }}
    strategy:
      fail-fast: true
      matrix:
        platform: ['x86_64','x86','armhf','armv7','aarch64','ppc64le','riscv64','s390x']
    steps:
      - uses: actions/checkout@v4
      - uses: jirutka/setup-alpine@v1
        with:
          # riscv64 currently requires 'edge'
          branch: edge
          arch: ${{ matrix.platform }}
          packages: >
            build-base
            meson
            libev-dev
            ragel
            glib-dev
            lua5.1-dev
            zlib-dev
            bzip2-dev
            pkgconf
            openssl-dev
            gnutls-dev
            libidn-dev
            libunwind-dev
            python3
            py3-curl
      - name: meson setup
        shell: alpine.sh {0}
        run: meson setup mesonbuilddir
      - name: meson compile
        shell: alpine.sh {0}
        run: meson compile -C mesonbuilddir
      - name: meson test
        shell: alpine.sh {0}
        run: meson test -C mesonbuilddir -v
